create table
  public.global_inventory (
    num_green_ml integer not null default 0,
    gold integer not null default 100,
    num_blue_ml integer not null default 0,
    num_red_ml integer not null default 0,
    num_dark_ml integer not null default 0,
    id integer generated by default as identity,
    constraint global_inventory_pkey primary key (id),
    constraint global_inventory_id_key unique (id)
  ) tablespace pg_default;

create table
  public.potions (
    potion_sku text not null default ''::text,
    red bigint not null default '0'::bigint,
    green bigint not null default '0'::bigint,
    blue bigint not null default '0'::bigint,
    dark bigint not null default '0'::bigint,
    price bigint not null default '0'::bigint,
    id bigint generated by default as identity,
    quantity bigint not null default '0'::bigint,
    name text not null default ''::text,
    increment bigint not null default '0'::bigint,
    constraint potions_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.customers (
    id bigint generated by default as identity,
    name text null default ''::text,
    class text null default ''::text,
    level bigint not null default '0'::bigint,
    "Edgeday" bigint not null default '0'::bigint,
    "Bloomday" bigint not null default '0'::bigint,
    "Aracanaday" bigint not null default '0'::bigint,
    "Hearthday" bigint not null default '0'::bigint,
    "Crownday" bigint not null default '0'::bigint,
    "Blesseday" bigint not null default '0'::bigint,
    "Soulday" bigint not null default '0'::bigint,
    constraint customers_pkey primary key (id),
    constraint unique_customer unique (name, class, level)
  ) tablespace pg_default;

  create table
  public.carts (
    id bigint generated by default as identity,
    customer_id bigint null,
    constraint Carts_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.cart_items (
    cart_id bigint not null,
    item_sku text not null default ''::text,
    item_qty bigint not null default '0'::bigint,
    date timestamp without time zone null default now(),
    constraint cart_items_pkey primary key (cart_id),
    constraint unique_cart_item unique (cart_id, item_sku)
  ) tablespace pg_default;

ALTER TABLE customers 
ADD CONSTRAINT unique_customer UNIQUE(name, class, level);

ALTER TABLE cart_items 
ADD CONSTRAINT unique_cart_item UNIQUE(cart_id, item_sku);

